source = colors.conf
general {
    disable_loading_bar = true
    hide_cursor = true
    ignore_empty_input = true
    grace = 0
    no_fade_in = false
}

animation {
    # fadeIn
    #bezier = snappy, 0.4, 0, 0.2, 1
    #bezier = smooth, 0.25, 0.1, 0.25, 1
    #bezier = bounce, 0.175, 0.885, 0.32, 1.275
    #bezier = material, 0.05, 0.7, 0.1, 1
    bezier = fast, 0, 0, 0, 1
    #bezier = pulse, 0.445, 0.05, 0.55, 0.95
    #bezier = quint, 0.83, 0, 0.17, 1
    #bezier = overshot, 0.05, 0.9, 0.1, 1.1
    # fade Out
    #bezier = instant, 1, 0, 1, 1
    #bezier = easeIn, 0.4, 0, 1, 1
    #bezier = quintIn, 0.64, 0, 0.78, 0
    bezier = appleOut, 0.7, 0, 0.2, 1
    #bezier = linear, 0, 0, 1, 1
    #bezier = incinerate, 0.8, 0, 1, 1
    # applying animations
    animation = fadeIn, 1, 6, fast
    animation = fadeOut, 1, 6, appleOut
}

background {
    monitor =
    path = $HOME/.config/hypr/car-in-grass.jpg
    blur_passes = 2
    blur_size = 4
    brightness = 0.6 
    vibrancy = 0.1
    noise = 0.01
}

# clock hours
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%H")"
    #text = $TIME
    color = $on_primary
    font_size = 100
    font_family = StretchPro
    halign = left
    valign = top
    position = 175, -175
}

# clock minutes
label {
    monitor =
    text = cmd[update:1000] echo "$(date +"%M")"
    color = $inverse_primary
    font_size = 95
    font_family = StretchPro
    halign = left
    valign = top
    position = 340, -220
}

# Cava
# equalizer
# label {
#    monitor =
#    text = cmd[update:1] echo "$(~/.config/hypr/golubchik/eq.sh)"
#    color = $on_primary
#    font_size = 22
#    # font_family = JetBrainsMono Nerd Font
#    position = 0, 0
#    halign = center
#    valign = bottom
# }

# CPU
label {
    monitor =
    text = cmd[update:5000] bash -c '\
        val=$(~/.config/hypr/golubchik/cpu_usage.sh); \
        bar=$(~/.config/hypr/golubchik/bar.sh $val 16); \
        printf "CPU  %s %3d%%" "$bar" "$val"'
    color = $primary
    font_size = 17
    # font_family = JetBrainsMono Nerd Font
    position = -300, 260
    halign = right
    valign = bottom
}

# GPU
label {
    monitor =
    text = cmd[update:5000] bash -c '\
        val=$(~/.config/hypr/golubchik/gpu_usage.sh); \
        bar=$(~/.config/hypr/golubchik/bar.sh $val 16); \
        printf "GPU  %s %3d%%" "$bar" "$val"'
    color = $on_primary
    font_size = 17
    # font_family = JetBrainsMono Nerd Font
    position = -250, 230
    halign = right
    valign = bottom
}

# MEMORY
label {
    monitor =
    text = cmd[update:5000] bash -c '\
        val=$(~/.config/hypr/golubchik/mem_usage.sh); \
        bar=$(~/.config/hypr/golubchik/bar.sh $val 16); \
        printf "MEM  %s %3d%%" "$bar" "$val"'
    color = $inverse_primary
    font_size = 17
    # font_family = JetBrainsMono Nerd Font
    position = -200, 200
    halign = right
    valign = bottom
}
