# wallpaper {
#     monitor = DP-1
#     path = $RIBYN_ROOT/assets/images/wallpapers/hypr_chan.png
#     fit_mode = cover
# }
#
# wallpaper {
#     monitor = DP-3
#     path = $RIBYN_ROOT/assets/images/wallpapers/hypr_lockscreen.png
#     fit_mode = cover
# }

wallpaper {
    monitor = 
    path = $RIBYN_ROOT/assets/images/wallpapers/hypr_chan.png
    fit_mode = cover
}
