# vim: ft=zsh
# shellcheck disable=SC2148
# shellcheck shell=zsh
#
# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
	source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

zmodload zsh/datetime
_start_time=$EPOCHREALTIME

# If you come from bash you might have to change your $PATH.
export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH
HISTCONTROL=ignoredups

# Path to your Oh My Zsh installation.
export ZSH="$HOME/.oh-my-zsh"

p10kfile="$HOME/.config/ribyn/zsh/p10k.zsh"
if [[ -f "$p10kfile" ]]; then
	ZSH_THEME="powerlevel10k/powerlevel10k"
else
	ZSH_THEME="avit"
fi

zstyle ':omz:update' mode reminder

# Uncomment the following line if you want to disable marking untracked files
# under VCS as dirty. This makes repository status check for large repositories
# much, much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

zstyle ':omz:plugins:nvm' lazy yes

plugins=(
	git
	zsh-vi-mode
	zsh-autosuggestions
	zsh-syntax-highlighting
	nvm 
	# adds around 120ms. on pc-white from 85ms -> 200+ms avrg.
)

# load zsh-completions not as a standard plugin but manually
# this prevents compinit from being called twice and significantly improves startup time
fpath+=${ZSH_CUSTOM:-${ZSH:-$HOME/.oh-my-zsh}/custom}/plugins/zsh-completions/src
autoload -U compinit && compinit

source $ZSH/oh-my-zsh.sh

export ZVM_KEYTIMEOUT="2" # 2s timeout e.g. for cs"'
# export ZVM_SYSTEM_CLIPBOARD_ENABLED=true NOTE: dont think i like this. should look for something else which copies the prompt for me

# User configuration

# export MANPATH="/usr/local/man:$MANPATH"

# You may need to manually set your language environment
# export LANG=en_US.UTF-8

export EDITOR='nvim'

export RIBYN_ROOT="$HOME/ribynlinux"
export PATH="$PATH:$RIBYN_ROOT/bin"
if [[ -d "$HOME/ribyns-state/bin" ]]; then
	export PATH="$PATH:$HOME/ribyns-state/bin"
fi

# treeview of all git tracked files (ripgrep respects .gitignore)
alias lstree='eza -1T'

alias gpl='git pull'
alias gpll='git pull && git log -1 --pretty=format:"%C(auto)%h%d%Creset %s %C(green)%cn%Creset %C(cyan)(%cr)%Creset"'

# override the defaults from the omz git plugin:
alias gpf='git push --force-with-lease' # exlude flag: --force-if-includes
alias gl='git log -7 --graph --pretty=format:"%C(auto)%h%d%Creset %s %C(green)%cn%Creset %C(cyan)(%cr)%Creset"'
alias gss='git status --short --untracked-files=all'
alias gce='git commit --allow-empty-message --no-edit --verbose'
alias gaacanepf='git add --all && git commit --amend --no-edit --verbose && git push --force-with-lease'

# shadow ls to use eza instead
alias ls='eza'
# lsdefault :)
alias lsd='eza -1 --group-directories-first --git-ignore'

alias mpdd='mpd --no-daemon &'
alias gourced="gource --no-vsync --fullscreen --auto-skip-seconds 1 --seconds-per-day 1"

alias dict="cat /usr/share/dict/words | fzf"

# prepend to take preceedence over windows/wsl passthrough paths
export PATH="$HOME/.dotnet:$HOME/.dotnet/tools:$PATH"
export DOTNET_ROOT="$HOME/.dotnet"
export DOTNET_ROOT_X64="$HOME/.dotnet"

export PATH="$PATH:$HOME/.cargo/bin"

if [[ -d "/home/linuxbrew/" ]]; then
	eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv zsh)"
fi

# find history (fzf a history cmd and select it for prompt editing and fire it off)
fh() {
	local choice
	choice=$(cut -d';' -f2 "$HISTFILE" | sort -u | uniq | grep '..........' | fzf)
	print -z "$choice"
}

ribyn() {
	local cmd="$1"

	if [[ "$cmd" == "root" ]]; then
		shift
		cd "$RIBYN_ROOT" || exit
	elif [[ "$cmd" == "state" ]]; then
		shift
		cd "$HOME/ribyns-state" || exit
	elif [[ "$cmd" == "run" ]]; then
		shift
		print -z "$( (
				fd . "$RIBYN_ROOT" --extension=sh
				fd . "$RIBYN_ROOT/bin"
			) | fzf)"
	elif [[ "$cmd" == "keyboard-feh" ]]; then
		shift
  	selected_img="$( (
				fd . "$RIBYN_ROOT/keyboard/glove80" --extension=png
			) | fzf)"
			if [[ -f "$selected_img" ]]; then
				feh "$selected_img"
			fi
	elif [[ "$cmd" == "keyboard-chafa-all" ]]; then
		shift
			chafa "$RIBYN_ROOT/keyboard/glove80/nav-layer.png"
			chafa "$RIBYN_ROOT/keyboard/glove80/symbol-fkeys-layer.png"
	elif [[ "$cmd" == "install" ]]; then
		shift
		"$RIBYN_ROOT/bin/ribyn_install"
	elif [[ "$cmd" == "sync" ]]; then
		shift
		"$RIBYN_ROOT/bin/ribyn_sync"
	else
		echo "ribyn: unknown key '$1'"
		for k in "${!temp_dirs[@]}"; do
			echo "  $k"
		done
		return 1
	fi
}
complete -W "root state run keyboard-feh keyboard-chafa keyboard-chafa-all" ribyn

# Then use y instead of yazi to start, and press q to quit, you'll see
# the CWD changed. Sometimes, you don't want to change, press Q to quit.
function y() {
	local tmp="$(mktemp -t "yazi-cwd.XXXXXX")" cwd
	command yazi "$@" --cwd-file="$tmp"
	IFS= read -r -d '' cwd <"$tmp"
	[ "$cwd" != "$PWD" ] && [ -d "$cwd" ] && builtin cd -- "$cwd"
	rm -f -- "$tmp"
}

zshlocal="$HOME/.config/ribyn/zsh/local.sh"
if [[ -f "$zshlocal" ]]; then
	source "$zshlocal"
fi

_total_ms=$(printf "%.2f" $((($EPOCHREALTIME - _start_time) * 1000)))
echo "${_total_ms}ms. $(date +%A,\ %Y-%m-%d\ %H:%M)"
echo "And whatever you do, do it heartily, as to the Lord and not to men, Colossians 3, 23 (NKJV)"
unset _start_time _total_ms

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
if [[ -f "$p10kfile"  ]]; then
	source $p10kfile
fi
