kitty_mod ctrl+shift

map kitty_mod+f5 load_config_file

font_family      family="CommitMono Nerd Font"
font_family      family="CommitMono"
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 14

map kitty_mod+minus  change_font_size all -1.0
map kitty_mod+plus   change_font_size all +1.0

# this needs to be set to "splits" otherwise the --localtion is ignored
enabled_layouts splits
map ctrl+shift+enter launch --cwd=current --location=vsplit
map ctrl+shift+backspace launch --cwd=current --location=hsplit

map ctrl+shift+t launch --cwd=current --type=tab
map ctrl+shift+h neighboring_window left
map ctrl+shift+l neighboring_window right
map ctrl+shift+k neighboring_window up
map ctrl+shift+j neighboring_window down
map kitty_mod+f10 toggle_maximized

include current-theme.conf

background #161616

tab_title_template          {title}{' :{}:'.format(num_windows) if num_windows > 1 else ''}

paste_actions no-op
enable_audio_bell no
hide_window_decorations yes # NOTE: for wsl you can create shortcut "C:\Program Files\WSL\wslg.exe" -d archlinux --cd "~" -- kitty --start-as maximized
confirm_os_window_close 0

tab_bar_edge                bottom
tab_bar_style powerline
tab_bar_min_tabs 2
tab_powerline_style         slanted

tab_powerline_style slanted

allow_remote_control yes
