# vim:ft=kitty

background_opacity 1

# using solid dark gray
background #161616

# using bg image
# background_image $HOME/.config/kitty/background.png
# background_tint 0.99
# background_image_layout scaled

