# prepend to take preceedence over windows/wsl passthrough paths
export PATH="$HOME/.dotnet:$HOME/.dotnet/tools:$PATH"

# dotnet decided without asking where to install dotnet.
# yet, without the env variable set, some dotnet tools dont
# know where it is. So we gotta help out :)
export DOTNET_ROOT="$HOME/.dotnet"
export DOTNET_ROOT_X64="$HOME/.dotnet"

export PATH="$PATH:$HOME/.cargo/bin"

# Append, to have manual install take preceedence.
# also appendedin mason, to have the same behavior (which deviates from the default)
export PATH="$PATH:$HOME/.local/share/nvim/mason/bin"

export HOMEBREW_NO_AUTO_UPDATE=1
export HOMEBREW_NO_ANALYTICS=1

export PATH=$HOME/bin:$HOME/.local/bin:/usr/local/bin:$PATH

export MANPATH="/usr/local/man:$MANPATH"

export EDITOR='nvim'

export RIBYN_ROOT="$HOME/ribynlinux"

# the directory name of the cursor theme located in "$HOME/.icons"
if [[ -d "$HOME/.icons/catppuccin-latte-mauve-cursors" ]]; then
	export XCURSOR_THEME="catppuccin-latte-mauve-cursors"
fi
# WARN: do not mistake with hyprland cursor themes
#
# xcursor and hyprcursor are both set in hyprland.lua
# to make sure hyprland knows about those env vars

# vim: ft=bash
