# zmodload zsh/zprof
# shellcheck disable=SC2148
# shellcheck shell=bash

# Path to your Oh My Zsh installation
export ZSH="$HOME/.oh-my-zsh"
export ZVM_KEYTIMEOUT="2" # 2s timeout e.g. for cs"'

setopt HIST_IGNORE_ALL_DUPS

zstyle ':omz:update' mode disabled
zstyle ':omz:plugins:nvm' lazy yes

# shellcheck disable=2034
plugins=(
	zsh-vi-mode
	zsh-autosuggestions
	zsh-syntax-highlighting
	nvm
)

# load zsh-completions not as a standard plugin but manually
# this prevents compinit from being called twice and significantly improves startup time
fpath+=${ZSH_CUSTOM:-$ZSH/custom}/plugins/zsh-completions/src
autoload -U compinit

source "$ZSH/oh-my-zsh.sh"

if [[ -d "/home/linuxbrew/" ]]; then
	eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv zsh)"
fi

eval "$(starship init zsh)"

source "$HOME/.config/ribyn/zsh/aliases"
source "$HOME/.config/ribyn/zsh/functions"
source "$HOME/.config/ribyn/zsh/gitrc"
source "$HOME/.config/ribyn/zsh/local.sh"

echo "And whatever you do, do it heartily, as to the Lord and not to men, Colossians 3:23 (NKJV)"

# zprof
# vim: ft=zsh
